# Generated by Django 2.2 on 2020-02-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='username',
        ),
    ]
