# Generated by Django 2.2 on 2020-02-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200211_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
